// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geometry_operators.proto

package epl_geometry

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//type of geometry operators
type GeometryEncodingType int32

const (
	GeometryEncodingType_unknown   GeometryEncodingType = 0
	GeometryEncodingType_wkb       GeometryEncodingType = 1
	GeometryEncodingType_wkt       GeometryEncodingType = 2
	GeometryEncodingType_geojson   GeometryEncodingType = 3
	GeometryEncodingType_esrishape GeometryEncodingType = 4
)

var GeometryEncodingType_name = map[int32]string{
	0: "unknown",
	1: "wkb",
	2: "wkt",
	3: "geojson",
	4: "esrishape",
}

var GeometryEncodingType_value = map[string]int32{
	"unknown":   0,
	"wkb":       1,
	"wkt":       2,
	"geojson":   3,
	"esrishape": 4,
}

func (x GeometryEncodingType) String() string {
	return proto.EnumName(GeometryEncodingType_name, int32(x))
}

func (GeometryEncodingType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{0}
}

//
//type of geometry operators
type ServiceOperatorType int32

const (
	ServiceOperatorType_Project                   ServiceOperatorType = 0
	ServiceOperatorType_ExportToJson              ServiceOperatorType = 1
	ServiceOperatorType_ImportFromJson            ServiceOperatorType = 2
	ServiceOperatorType_ImportMapGeometryFromJson ServiceOperatorType = 3
	ServiceOperatorType_ExportToESRIShape         ServiceOperatorType = 4
	ServiceOperatorType_ImportFromESRIShape       ServiceOperatorType = 5
	ServiceOperatorType_Union                     ServiceOperatorType = 6
	ServiceOperatorType_Difference                ServiceOperatorType = 7
	ServiceOperatorType_Proximity2D               ServiceOperatorType = 8
	ServiceOperatorType_Relate                    ServiceOperatorType = 9
	ServiceOperatorType_Equals                    ServiceOperatorType = 10
	ServiceOperatorType_Disjoint                  ServiceOperatorType = 11
	ServiceOperatorType_Intersects                ServiceOperatorType = 12
	ServiceOperatorType_Within                    ServiceOperatorType = 13
	ServiceOperatorType_Contains                  ServiceOperatorType = 14
	ServiceOperatorType_Crosses                   ServiceOperatorType = 15
	ServiceOperatorType_Touches                   ServiceOperatorType = 16
	ServiceOperatorType_Overlaps                  ServiceOperatorType = 17
	ServiceOperatorType_Buffer                    ServiceOperatorType = 18
	ServiceOperatorType_Distance                  ServiceOperatorType = 19
	ServiceOperatorType_Intersection              ServiceOperatorType = 20
	ServiceOperatorType_Clip                      ServiceOperatorType = 21
	ServiceOperatorType_Cut                       ServiceOperatorType = 22
	ServiceOperatorType_DensifyByLength           ServiceOperatorType = 23
	ServiceOperatorType_GeodesicBuffer            ServiceOperatorType = 26
	ServiceOperatorType_GeodeticDensifyByLength   ServiceOperatorType = 27
	// ShapePreservingDensify = 28;
	ServiceOperatorType_GeodeticLength      ServiceOperatorType = 29
	ServiceOperatorType_Simplify            ServiceOperatorType = 31
	ServiceOperatorType_SimplifyOGC         ServiceOperatorType = 32
	ServiceOperatorType_Offset              ServiceOperatorType = 33
	ServiceOperatorType_Generalize          ServiceOperatorType = 34
	ServiceOperatorType_GeneralizeByArea    ServiceOperatorType = 35
	ServiceOperatorType_ExportToWkb         ServiceOperatorType = 36
	ServiceOperatorType_ImportFromWkb       ServiceOperatorType = 37
	ServiceOperatorType_ExportToWkt         ServiceOperatorType = 38
	ServiceOperatorType_ImportFromWkt       ServiceOperatorType = 39
	ServiceOperatorType_ImportFromGeoJson   ServiceOperatorType = 40
	ServiceOperatorType_ExportToGeoJson     ServiceOperatorType = 41
	ServiceOperatorType_SymmetricDifference ServiceOperatorType = 42
	ServiceOperatorType_ConvexHull          ServiceOperatorType = 43
	ServiceOperatorType_Boundary            ServiceOperatorType = 44
	ServiceOperatorType_RandomPoints        ServiceOperatorType = 45
	ServiceOperatorType_EnclosingCircle     ServiceOperatorType = 46
)

var ServiceOperatorType_name = map[int32]string{
	0:  "Project",
	1:  "ExportToJson",
	2:  "ImportFromJson",
	3:  "ImportMapGeometryFromJson",
	4:  "ExportToESRIShape",
	5:  "ImportFromESRIShape",
	6:  "Union",
	7:  "Difference",
	8:  "Proximity2D",
	9:  "Relate",
	10: "Equals",
	11: "Disjoint",
	12: "Intersects",
	13: "Within",
	14: "Contains",
	15: "Crosses",
	16: "Touches",
	17: "Overlaps",
	18: "Buffer",
	19: "Distance",
	20: "Intersection",
	21: "Clip",
	22: "Cut",
	23: "DensifyByLength",
	26: "GeodesicBuffer",
	27: "GeodeticDensifyByLength",
	29: "GeodeticLength",
	31: "Simplify",
	32: "SimplifyOGC",
	33: "Offset",
	34: "Generalize",
	35: "GeneralizeByArea",
	36: "ExportToWkb",
	37: "ImportFromWkb",
	38: "ExportToWkt",
	39: "ImportFromWkt",
	40: "ImportFromGeoJson",
	41: "ExportToGeoJson",
	42: "SymmetricDifference",
	43: "ConvexHull",
	44: "Boundary",
	45: "RandomPoints",
	46: "EnclosingCircle",
}

var ServiceOperatorType_value = map[string]int32{
	"Project":                   0,
	"ExportToJson":              1,
	"ImportFromJson":            2,
	"ImportMapGeometryFromJson": 3,
	"ExportToESRIShape":         4,
	"ImportFromESRIShape":       5,
	"Union":                     6,
	"Difference":                7,
	"Proximity2D":               8,
	"Relate":                    9,
	"Equals":                    10,
	"Disjoint":                  11,
	"Intersects":                12,
	"Within":                    13,
	"Contains":                  14,
	"Crosses":                   15,
	"Touches":                   16,
	"Overlaps":                  17,
	"Buffer":                    18,
	"Distance":                  19,
	"Intersection":              20,
	"Clip":                      21,
	"Cut":                       22,
	"DensifyByLength":           23,
	"GeodesicBuffer":            26,
	"GeodeticDensifyByLength":   27,
	"GeodeticLength":            29,
	"Simplify":                  31,
	"SimplifyOGC":               32,
	"Offset":                    33,
	"Generalize":                34,
	"GeneralizeByArea":          35,
	"ExportToWkb":               36,
	"ImportFromWkb":             37,
	"ExportToWkt":               38,
	"ImportFromWkt":             39,
	"ImportFromGeoJson":         40,
	"ExportToGeoJson":           41,
	"SymmetricDifference":       42,
	"ConvexHull":                43,
	"Boundary":                  44,
	"RandomPoints":              45,
	"EnclosingCircle":           46,
}

func (x ServiceOperatorType) String() string {
	return proto.EnumName(ServiceOperatorType_name, int32(x))
}

func (ServiceOperatorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{1}
}

type OffsetJoinType int32

const (
	OffsetJoinType_Round  OffsetJoinType = 0
	OffsetJoinType_Bevel  OffsetJoinType = 1
	OffsetJoinType_Miter  OffsetJoinType = 2
	OffsetJoinType_Square OffsetJoinType = 3
)

var OffsetJoinType_name = map[int32]string{
	0: "Round",
	1: "Bevel",
	2: "Miter",
	3: "Square",
}

var OffsetJoinType_value = map[string]int32{
	"Round":  0,
	"Bevel":  1,
	"Miter":  2,
	"Square": 3,
}

func (x OffsetJoinType) String() string {
	return proto.EnumName(OffsetJoinType_name, int32(x))
}

func (OffsetJoinType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{2}
}

type FileType int32

const (
	FileType_Shapefile FileType = 0
)

var FileType_name = map[int32]string{
	0: "Shapefile",
}

var FileType_value = map[string]int32{
	"Shapefile": 0,
}

func (x FileType) String() string {
	return proto.EnumName(FileType_name, int32(x))
}

func (FileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{3}
}

type GeometryBagData struct {
	// oneof block start
	GeometryIds []int64  `protobuf:"varint,1,rep,packed,name=geometry_ids,json=geometryIds,proto3" json:"geometry_ids,omitempty"`
	FeatureIds  []string `protobuf:"bytes,9,rep,name=feature_ids,json=featureIds,proto3" json:"feature_ids,omitempty"`
	// type can be 'wkt', 'wkb', 'geojson', or 'esri'
	GeometryEncodingType GeometryEncodingType  `protobuf:"varint,2,opt,name=geometry_encoding_type,json=geometryEncodingType,proto3,enum=epl.geometry.GeometryEncodingType" json:"geometry_encoding_type,omitempty"`
	Wkt                  []string              `protobuf:"bytes,3,rep,name=wkt,proto3" json:"wkt,omitempty"`
	Geojson              []string              `protobuf:"bytes,4,rep,name=geojson,proto3" json:"geojson,omitempty"`
	Wkb                  [][]byte              `protobuf:"bytes,5,rep,name=wkb,proto3" json:"wkb,omitempty"`
	EsriShape            [][]byte              `protobuf:"bytes,6,rep,name=esri_shape,json=esriShape,proto3" json:"esri_shape,omitempty"`
	SpatialReference     *SpatialReferenceData `protobuf:"bytes,7,opt,name=spatial_reference,json=spatialReference,proto3" json:"spatial_reference,omitempty"`
	EsriJson             []string              `protobuf:"bytes,8,rep,name=esri_json,json=esriJson,proto3" json:"esri_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GeometryBagData) Reset()         { *m = GeometryBagData{} }
func (m *GeometryBagData) String() string { return proto.CompactTextString(m) }
func (*GeometryBagData) ProtoMessage()    {}
func (*GeometryBagData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{0}
}

func (m *GeometryBagData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeometryBagData.Unmarshal(m, b)
}
func (m *GeometryBagData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeometryBagData.Marshal(b, m, deterministic)
}
func (m *GeometryBagData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeometryBagData.Merge(m, src)
}
func (m *GeometryBagData) XXX_Size() int {
	return xxx_messageInfo_GeometryBagData.Size(m)
}
func (m *GeometryBagData) XXX_DiscardUnknown() {
	xxx_messageInfo_GeometryBagData.DiscardUnknown(m)
}

var xxx_messageInfo_GeometryBagData proto.InternalMessageInfo

func (m *GeometryBagData) GetGeometryIds() []int64 {
	if m != nil {
		return m.GeometryIds
	}
	return nil
}

func (m *GeometryBagData) GetFeatureIds() []string {
	if m != nil {
		return m.FeatureIds
	}
	return nil
}

func (m *GeometryBagData) GetGeometryEncodingType() GeometryEncodingType {
	if m != nil {
		return m.GeometryEncodingType
	}
	return GeometryEncodingType_unknown
}

func (m *GeometryBagData) GetWkt() []string {
	if m != nil {
		return m.Wkt
	}
	return nil
}

func (m *GeometryBagData) GetGeojson() []string {
	if m != nil {
		return m.Geojson
	}
	return nil
}

func (m *GeometryBagData) GetWkb() [][]byte {
	if m != nil {
		return m.Wkb
	}
	return nil
}

func (m *GeometryBagData) GetEsriShape() [][]byte {
	if m != nil {
		return m.EsriShape
	}
	return nil
}

func (m *GeometryBagData) GetSpatialReference() *SpatialReferenceData {
	if m != nil {
		return m.SpatialReference
	}
	return nil
}

func (m *GeometryBagData) GetEsriJson() []string {
	if m != nil {
		return m.EsriJson
	}
	return nil
}

type SpatialReferenceData struct {
	Proj4 string `protobuf:"bytes,4,opt,name=proj4,proto3" json:"proj4,omitempty"`
	// String that is a wkt, wkid, esri_wkt, or a proj4 string
	EsriWkt string `protobuf:"bytes,5,opt,name=esri_wkt,json=esriWkt,proto3" json:"esri_wkt,omitempty"`
	// type is either 'wkid', 'esri_wkt'
	Wkid                 int32    `protobuf:"varint,6,opt,name=wkid,proto3" json:"wkid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpatialReferenceData) Reset()         { *m = SpatialReferenceData{} }
func (m *SpatialReferenceData) String() string { return proto.CompactTextString(m) }
func (*SpatialReferenceData) ProtoMessage()    {}
func (*SpatialReferenceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{1}
}

func (m *SpatialReferenceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpatialReferenceData.Unmarshal(m, b)
}
func (m *SpatialReferenceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpatialReferenceData.Marshal(b, m, deterministic)
}
func (m *SpatialReferenceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpatialReferenceData.Merge(m, src)
}
func (m *SpatialReferenceData) XXX_Size() int {
	return xxx_messageInfo_SpatialReferenceData.Size(m)
}
func (m *SpatialReferenceData) XXX_DiscardUnknown() {
	xxx_messageInfo_SpatialReferenceData.DiscardUnknown(m)
}

var xxx_messageInfo_SpatialReferenceData proto.InternalMessageInfo

func (m *SpatialReferenceData) GetProj4() string {
	if m != nil {
		return m.Proj4
	}
	return ""
}

func (m *SpatialReferenceData) GetEsriWkt() string {
	if m != nil {
		return m.EsriWkt
	}
	return ""
}

func (m *SpatialReferenceData) GetWkid() int32 {
	if m != nil {
		return m.Wkid
	}
	return 0
}

type OperatorResult struct {
	GeometryBag          *GeometryBagData `protobuf:"bytes,1,opt,name=geometry_bag,json=geometryBag,proto3" json:"geometry_bag,omitempty"`
	SpatialRelationship  bool             `protobuf:"varint,2,opt,name=spatial_relationship,json=spatialRelationship,proto3" json:"spatial_relationship,omitempty"`
	Distance             float64          `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"`
	RelateMap            map[int64]bool   `protobuf:"bytes,4,rep,name=relate_map,json=relateMap,proto3" json:"relate_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OperatorResult) Reset()         { *m = OperatorResult{} }
func (m *OperatorResult) String() string { return proto.CompactTextString(m) }
func (*OperatorResult) ProtoMessage()    {}
func (*OperatorResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{2}
}

func (m *OperatorResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorResult.Unmarshal(m, b)
}
func (m *OperatorResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorResult.Marshal(b, m, deterministic)
}
func (m *OperatorResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorResult.Merge(m, src)
}
func (m *OperatorResult) XXX_Size() int {
	return xxx_messageInfo_OperatorResult.Size(m)
}
func (m *OperatorResult) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorResult.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorResult proto.InternalMessageInfo

func (m *OperatorResult) GetGeometryBag() *GeometryBagData {
	if m != nil {
		return m.GeometryBag
	}
	return nil
}

func (m *OperatorResult) GetSpatialRelationship() bool {
	if m != nil {
		return m.SpatialRelationship
	}
	return false
}

func (m *OperatorResult) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *OperatorResult) GetRelateMap() map[int64]bool {
	if m != nil {
		return m.RelateMap
	}
	return nil
}

type FileChunk struct {
	NestedRequest          *OperatorRequest      `protobuf:"bytes,1,opt,name=nested_request,json=nestedRequest,proto3" json:"nested_request,omitempty"`
	ResultsEncodingType    GeometryEncodingType  `protobuf:"varint,2,opt,name=results_encoding_type,json=resultsEncodingType,proto3,enum=epl.geometry.GeometryEncodingType" json:"results_encoding_type,omitempty"`
	InputSpatialReference  *SpatialReferenceData `protobuf:"bytes,3,opt,name=input_spatial_reference,json=inputSpatialReference,proto3" json:"input_spatial_reference,omitempty"`
	ResultSpatialReference *SpatialReferenceData `protobuf:"bytes,5,opt,name=result_spatial_reference,json=resultSpatialReference,proto3" json:"result_spatial_reference,omitempty"`
	Data                   []byte                `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Size                   int64                 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Offset                 int64                 `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	FileName               string                `protobuf:"bytes,9,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	IsLastChunk            bool                  `protobuf:"varint,10,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}              `json:"-"`
	XXX_unrecognized       []byte                `json:"-"`
	XXX_sizecache          int32                 `json:"-"`
}

func (m *FileChunk) Reset()         { *m = FileChunk{} }
func (m *FileChunk) String() string { return proto.CompactTextString(m) }
func (*FileChunk) ProtoMessage()    {}
func (*FileChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{3}
}

func (m *FileChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileChunk.Unmarshal(m, b)
}
func (m *FileChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileChunk.Marshal(b, m, deterministic)
}
func (m *FileChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileChunk.Merge(m, src)
}
func (m *FileChunk) XXX_Size() int {
	return xxx_messageInfo_FileChunk.Size(m)
}
func (m *FileChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_FileChunk.DiscardUnknown(m)
}

var xxx_messageInfo_FileChunk proto.InternalMessageInfo

func (m *FileChunk) GetNestedRequest() *OperatorRequest {
	if m != nil {
		return m.NestedRequest
	}
	return nil
}

func (m *FileChunk) GetResultsEncodingType() GeometryEncodingType {
	if m != nil {
		return m.ResultsEncodingType
	}
	return GeometryEncodingType_unknown
}

func (m *FileChunk) GetInputSpatialReference() *SpatialReferenceData {
	if m != nil {
		return m.InputSpatialReference
	}
	return nil
}

func (m *FileChunk) GetResultSpatialReference() *SpatialReferenceData {
	if m != nil {
		return m.ResultSpatialReference
	}
	return nil
}

func (m *FileChunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *FileChunk) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileChunk) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FileChunk) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileChunk) GetIsLastChunk() bool {
	if m != nil {
		return m.IsLastChunk
	}
	return false
}

type BufferParams struct {
	Distances               []float64 `protobuf:"fixed64,1,rep,packed,name=distances,proto3" json:"distances,omitempty"`
	MaxDeviations           []float64 `protobuf:"fixed64,2,rep,packed,name=max_deviations,json=maxDeviations,proto3" json:"max_deviations,omitempty"`
	UnionResult             bool      `protobuf:"varint,3,opt,name=union_result,json=unionResult,proto3" json:"union_result,omitempty"`
	MaxVerticesInFullCircle int32     `protobuf:"varint,4,opt,name=max_vertices_in_full_circle,json=maxVerticesInFullCircle,proto3" json:"max_vertices_in_full_circle,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}  `json:"-"`
	XXX_unrecognized        []byte    `json:"-"`
	XXX_sizecache           int32     `json:"-"`
}

func (m *BufferParams) Reset()         { *m = BufferParams{} }
func (m *BufferParams) String() string { return proto.CompactTextString(m) }
func (*BufferParams) ProtoMessage()    {}
func (*BufferParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{4}
}

func (m *BufferParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BufferParams.Unmarshal(m, b)
}
func (m *BufferParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BufferParams.Marshal(b, m, deterministic)
}
func (m *BufferParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BufferParams.Merge(m, src)
}
func (m *BufferParams) XXX_Size() int {
	return xxx_messageInfo_BufferParams.Size(m)
}
func (m *BufferParams) XXX_DiscardUnknown() {
	xxx_messageInfo_BufferParams.DiscardUnknown(m)
}

var xxx_messageInfo_BufferParams proto.InternalMessageInfo

func (m *BufferParams) GetDistances() []float64 {
	if m != nil {
		return m.Distances
	}
	return nil
}

func (m *BufferParams) GetMaxDeviations() []float64 {
	if m != nil {
		return m.MaxDeviations
	}
	return nil
}

func (m *BufferParams) GetUnionResult() bool {
	if m != nil {
		return m.UnionResult
	}
	return false
}

func (m *BufferParams) GetMaxVerticesInFullCircle() int32 {
	if m != nil {
		return m.MaxVerticesInFullCircle
	}
	return 0
}

type GeodeticBufferParams struct {
	Distances               []float64 `protobuf:"fixed64,1,rep,packed,name=distances,proto3" json:"distances,omitempty"`
	MaxDeviations           []float64 `protobuf:"fixed64,2,rep,packed,name=max_deviations,json=maxDeviations,proto3" json:"max_deviations,omitempty"`
	UnionResult             bool      `protobuf:"varint,3,opt,name=union_result,json=unionResult,proto3" json:"union_result,omitempty"`
	MaxVerticesInFullCircle int32     `protobuf:"varint,4,opt,name=max_vertices_in_full_circle,json=maxVerticesInFullCircle,proto3" json:"max_vertices_in_full_circle,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}  `json:"-"`
	XXX_unrecognized        []byte    `json:"-"`
	XXX_sizecache           int32     `json:"-"`
}

func (m *GeodeticBufferParams) Reset()         { *m = GeodeticBufferParams{} }
func (m *GeodeticBufferParams) String() string { return proto.CompactTextString(m) }
func (*GeodeticBufferParams) ProtoMessage()    {}
func (*GeodeticBufferParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{5}
}

func (m *GeodeticBufferParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeodeticBufferParams.Unmarshal(m, b)
}
func (m *GeodeticBufferParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeodeticBufferParams.Marshal(b, m, deterministic)
}
func (m *GeodeticBufferParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeodeticBufferParams.Merge(m, src)
}
func (m *GeodeticBufferParams) XXX_Size() int {
	return xxx_messageInfo_GeodeticBufferParams.Size(m)
}
func (m *GeodeticBufferParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GeodeticBufferParams.DiscardUnknown(m)
}

var xxx_messageInfo_GeodeticBufferParams proto.InternalMessageInfo

func (m *GeodeticBufferParams) GetDistances() []float64 {
	if m != nil {
		return m.Distances
	}
	return nil
}

func (m *GeodeticBufferParams) GetMaxDeviations() []float64 {
	if m != nil {
		return m.MaxDeviations
	}
	return nil
}

func (m *GeodeticBufferParams) GetUnionResult() bool {
	if m != nil {
		return m.UnionResult
	}
	return false
}

func (m *GeodeticBufferParams) GetMaxVerticesInFullCircle() int32 {
	if m != nil {
		return m.MaxVerticesInFullCircle
	}
	return 0
}

type ConvexParams struct {
	Merge                bool     `protobuf:"varint,1,opt,name=merge,proto3" json:"merge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvexParams) Reset()         { *m = ConvexParams{} }
func (m *ConvexParams) String() string { return proto.CompactTextString(m) }
func (*ConvexParams) ProtoMessage()    {}
func (*ConvexParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{6}
}

func (m *ConvexParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvexParams.Unmarshal(m, b)
}
func (m *ConvexParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvexParams.Marshal(b, m, deterministic)
}
func (m *ConvexParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvexParams.Merge(m, src)
}
func (m *ConvexParams) XXX_Size() int {
	return xxx_messageInfo_ConvexParams.Size(m)
}
func (m *ConvexParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvexParams.DiscardUnknown(m)
}

var xxx_messageInfo_ConvexParams proto.InternalMessageInfo

func (m *ConvexParams) GetMerge() bool {
	if m != nil {
		return m.Merge
	}
	return false
}

type RelateParams struct {
	De_9Im               string   `protobuf:"bytes,1,opt,name=de_9im,json=de9im,proto3" json:"de_9im,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelateParams) Reset()         { *m = RelateParams{} }
func (m *RelateParams) String() string { return proto.CompactTextString(m) }
func (*RelateParams) ProtoMessage()    {}
func (*RelateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{7}
}

func (m *RelateParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelateParams.Unmarshal(m, b)
}
func (m *RelateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelateParams.Marshal(b, m, deterministic)
}
func (m *RelateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelateParams.Merge(m, src)
}
func (m *RelateParams) XXX_Size() int {
	return xxx_messageInfo_RelateParams.Size(m)
}
func (m *RelateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RelateParams.DiscardUnknown(m)
}

var xxx_messageInfo_RelateParams proto.InternalMessageInfo

func (m *RelateParams) GetDe_9Im() string {
	if m != nil {
		return m.De_9Im
	}
	return ""
}

type RandomPointsParams struct {
	PointsPerSquareKm    []float64 `protobuf:"fixed64,1,rep,packed,name=points_per_square_km,json=pointsPerSquareKm,proto3" json:"points_per_square_km,omitempty"`
	Seed                 int64     `protobuf:"varint,2,opt,name=seed,proto3" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RandomPointsParams) Reset()         { *m = RandomPointsParams{} }
func (m *RandomPointsParams) String() string { return proto.CompactTextString(m) }
func (*RandomPointsParams) ProtoMessage()    {}
func (*RandomPointsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{8}
}

func (m *RandomPointsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomPointsParams.Unmarshal(m, b)
}
func (m *RandomPointsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomPointsParams.Marshal(b, m, deterministic)
}
func (m *RandomPointsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomPointsParams.Merge(m, src)
}
func (m *RandomPointsParams) XXX_Size() int {
	return xxx_messageInfo_RandomPointsParams.Size(m)
}
func (m *RandomPointsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomPointsParams.DiscardUnknown(m)
}

var xxx_messageInfo_RandomPointsParams proto.InternalMessageInfo

func (m *RandomPointsParams) GetPointsPerSquareKm() []float64 {
	if m != nil {
		return m.PointsPerSquareKm
	}
	return nil
}

func (m *RandomPointsParams) GetSeed() int64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

type GeneralizeParams struct {
	MaxDeviation         float64  `protobuf:"fixed64,1,opt,name=max_deviation,json=maxDeviation,proto3" json:"max_deviation,omitempty"`
	RemoveDegenerates    bool     `protobuf:"varint,2,opt,name=remove_degenerates,json=removeDegenerates,proto3" json:"remove_degenerates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralizeParams) Reset()         { *m = GeneralizeParams{} }
func (m *GeneralizeParams) String() string { return proto.CompactTextString(m) }
func (*GeneralizeParams) ProtoMessage()    {}
func (*GeneralizeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{9}
}

func (m *GeneralizeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralizeParams.Unmarshal(m, b)
}
func (m *GeneralizeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralizeParams.Marshal(b, m, deterministic)
}
func (m *GeneralizeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralizeParams.Merge(m, src)
}
func (m *GeneralizeParams) XXX_Size() int {
	return xxx_messageInfo_GeneralizeParams.Size(m)
}
func (m *GeneralizeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralizeParams.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralizeParams proto.InternalMessageInfo

func (m *GeneralizeParams) GetMaxDeviation() float64 {
	if m != nil {
		return m.MaxDeviation
	}
	return 0
}

func (m *GeneralizeParams) GetRemoveDegenerates() bool {
	if m != nil {
		return m.RemoveDegenerates
	}
	return false
}

type GeneralizeByAreaParams struct {
	PercentReduction     float64  `protobuf:"fixed64,1,opt,name=percent_reduction,json=percentReduction,proto3" json:"percent_reduction,omitempty"`
	RemoveDegenerates    bool     `protobuf:"varint,2,opt,name=remove_degenerates,json=removeDegenerates,proto3" json:"remove_degenerates,omitempty"`
	MaxPointCount        int32    `protobuf:"varint,3,opt,name=max_point_count,json=maxPointCount,proto3" json:"max_point_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralizeByAreaParams) Reset()         { *m = GeneralizeByAreaParams{} }
func (m *GeneralizeByAreaParams) String() string { return proto.CompactTextString(m) }
func (*GeneralizeByAreaParams) ProtoMessage()    {}
func (*GeneralizeByAreaParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{10}
}

func (m *GeneralizeByAreaParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralizeByAreaParams.Unmarshal(m, b)
}
func (m *GeneralizeByAreaParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralizeByAreaParams.Marshal(b, m, deterministic)
}
func (m *GeneralizeByAreaParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralizeByAreaParams.Merge(m, src)
}
func (m *GeneralizeByAreaParams) XXX_Size() int {
	return xxx_messageInfo_GeneralizeByAreaParams.Size(m)
}
func (m *GeneralizeByAreaParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralizeByAreaParams.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralizeByAreaParams proto.InternalMessageInfo

func (m *GeneralizeByAreaParams) GetPercentReduction() float64 {
	if m != nil {
		return m.PercentReduction
	}
	return 0
}

func (m *GeneralizeByAreaParams) GetRemoveDegenerates() bool {
	if m != nil {
		return m.RemoveDegenerates
	}
	return false
}

func (m *GeneralizeByAreaParams) GetMaxPointCount() int32 {
	if m != nil {
		return m.MaxPointCount
	}
	return 0
}

type IntersectionParams struct {
	DimensionMask        int32    `protobuf:"varint,1,opt,name=dimension_mask,json=dimensionMask,proto3" json:"dimension_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntersectionParams) Reset()         { *m = IntersectionParams{} }
func (m *IntersectionParams) String() string { return proto.CompactTextString(m) }
func (*IntersectionParams) ProtoMessage()    {}
func (*IntersectionParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{11}
}

func (m *IntersectionParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntersectionParams.Unmarshal(m, b)
}
func (m *IntersectionParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntersectionParams.Marshal(b, m, deterministic)
}
func (m *IntersectionParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntersectionParams.Merge(m, src)
}
func (m *IntersectionParams) XXX_Size() int {
	return xxx_messageInfo_IntersectionParams.Size(m)
}
func (m *IntersectionParams) XXX_DiscardUnknown() {
	xxx_messageInfo_IntersectionParams.DiscardUnknown(m)
}

var xxx_messageInfo_IntersectionParams proto.InternalMessageInfo

func (m *IntersectionParams) GetDimensionMask() int32 {
	if m != nil {
		return m.DimensionMask
	}
	return 0
}

type OffsetParams struct {
	Distance             float64        `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`
	JoinType             OffsetJoinType `protobuf:"varint,2,opt,name=join_type,json=joinType,proto3,enum=epl.geometry.OffsetJoinType" json:"join_type,omitempty"`
	BevelRatio           float64        `protobuf:"fixed64,3,opt,name=bevel_ratio,json=bevelRatio,proto3" json:"bevel_ratio,omitempty"`
	FlattenError         float64        `protobuf:"fixed64,4,opt,name=flatten_error,json=flattenError,proto3" json:"flatten_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *OffsetParams) Reset()         { *m = OffsetParams{} }
func (m *OffsetParams) String() string { return proto.CompactTextString(m) }
func (*OffsetParams) ProtoMessage()    {}
func (*OffsetParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{12}
}

func (m *OffsetParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OffsetParams.Unmarshal(m, b)
}
func (m *OffsetParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OffsetParams.Marshal(b, m, deterministic)
}
func (m *OffsetParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OffsetParams.Merge(m, src)
}
func (m *OffsetParams) XXX_Size() int {
	return xxx_messageInfo_OffsetParams.Size(m)
}
func (m *OffsetParams) XXX_DiscardUnknown() {
	xxx_messageInfo_OffsetParams.DiscardUnknown(m)
}

var xxx_messageInfo_OffsetParams proto.InternalMessageInfo

func (m *OffsetParams) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *OffsetParams) GetJoinType() OffsetJoinType {
	if m != nil {
		return m.JoinType
	}
	return OffsetJoinType_Round
}

func (m *OffsetParams) GetBevelRatio() float64 {
	if m != nil {
		return m.BevelRatio
	}
	return 0
}

func (m *OffsetParams) GetFlattenError() float64 {
	if m != nil {
		return m.FlattenError
	}
	return 0
}

type CutParams struct {
	ConsiderTouch        bool     `protobuf:"varint,1,opt,name=consider_touch,json=considerTouch,proto3" json:"consider_touch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CutParams) Reset()         { *m = CutParams{} }
func (m *CutParams) String() string { return proto.CompactTextString(m) }
func (*CutParams) ProtoMessage()    {}
func (*CutParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{13}
}

func (m *CutParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CutParams.Unmarshal(m, b)
}
func (m *CutParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CutParams.Marshal(b, m, deterministic)
}
func (m *CutParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CutParams.Merge(m, src)
}
func (m *CutParams) XXX_Size() int {
	return xxx_messageInfo_CutParams.Size(m)
}
func (m *CutParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CutParams.DiscardUnknown(m)
}

var xxx_messageInfo_CutParams proto.InternalMessageInfo

func (m *CutParams) GetConsiderTouch() bool {
	if m != nil {
		return m.ConsiderTouch
	}
	return false
}

type ClipParams struct {
	Envelope             *EnvelopeData `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ClipParams) Reset()         { *m = ClipParams{} }
func (m *ClipParams) String() string { return proto.CompactTextString(m) }
func (*ClipParams) ProtoMessage()    {}
func (*ClipParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{14}
}

func (m *ClipParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClipParams.Unmarshal(m, b)
}
func (m *ClipParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClipParams.Marshal(b, m, deterministic)
}
func (m *ClipParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClipParams.Merge(m, src)
}
func (m *ClipParams) XXX_Size() int {
	return xxx_messageInfo_ClipParams.Size(m)
}
func (m *ClipParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ClipParams.DiscardUnknown(m)
}

var xxx_messageInfo_ClipParams proto.InternalMessageInfo

func (m *ClipParams) GetEnvelope() *EnvelopeData {
	if m != nil {
		return m.Envelope
	}
	return nil
}

type DensifyParams struct {
	MaxLength            float64  `protobuf:"fixed64,1,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DensifyParams) Reset()         { *m = DensifyParams{} }
func (m *DensifyParams) String() string { return proto.CompactTextString(m) }
func (*DensifyParams) ProtoMessage()    {}
func (*DensifyParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{15}
}

func (m *DensifyParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DensifyParams.Unmarshal(m, b)
}
func (m *DensifyParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DensifyParams.Marshal(b, m, deterministic)
}
func (m *DensifyParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DensifyParams.Merge(m, src)
}
func (m *DensifyParams) XXX_Size() int {
	return xxx_messageInfo_DensifyParams.Size(m)
}
func (m *DensifyParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DensifyParams.DiscardUnknown(m)
}

var xxx_messageInfo_DensifyParams proto.InternalMessageInfo

func (m *DensifyParams) GetMaxLength() float64 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

type SimplifyParams struct {
	Force                bool     `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimplifyParams) Reset()         { *m = SimplifyParams{} }
func (m *SimplifyParams) String() string { return proto.CompactTextString(m) }
func (*SimplifyParams) ProtoMessage()    {}
func (*SimplifyParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{16}
}

func (m *SimplifyParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimplifyParams.Unmarshal(m, b)
}
func (m *SimplifyParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimplifyParams.Marshal(b, m, deterministic)
}
func (m *SimplifyParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimplifyParams.Merge(m, src)
}
func (m *SimplifyParams) XXX_Size() int {
	return xxx_messageInfo_SimplifyParams.Size(m)
}
func (m *SimplifyParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SimplifyParams.DiscardUnknown(m)
}

var xxx_messageInfo_SimplifyParams proto.InternalMessageInfo

func (m *SimplifyParams) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type OperatorRequest struct {
	//    oneof primary_geoms {
	GeometryBag         *GeometryBagData `protobuf:"bytes,1,opt,name=geometry_bag,json=geometryBag,proto3" json:"geometry_bag,omitempty"`
	GeometryRequest     *OperatorRequest `protobuf:"bytes,2,opt,name=geometry_request,json=geometryRequest,proto3" json:"geometry_request,omitempty"`
	LeftGeometryBag     *GeometryBagData `protobuf:"bytes,3,opt,name=left_geometry_bag,json=leftGeometryBag,proto3" json:"left_geometry_bag,omitempty"`
	LeftGeometryRequest *OperatorRequest `protobuf:"bytes,4,opt,name=left_geometry_request,json=leftGeometryRequest,proto3" json:"left_geometry_request,omitempty"`
	//    oneof secondary_geoms {
	RightGeometryBag          *GeometryBagData      `protobuf:"bytes,5,opt,name=right_geometry_bag,json=rightGeometryBag,proto3" json:"right_geometry_bag,omitempty"`
	RightGeometryRequest      *OperatorRequest      `protobuf:"bytes,6,opt,name=right_geometry_request,json=rightGeometryRequest,proto3" json:"right_geometry_request,omitempty"`
	OperatorType              ServiceOperatorType   `protobuf:"varint,7,opt,name=operator_type,json=operatorType,proto3,enum=epl.geometry.ServiceOperatorType" json:"operator_type,omitempty"`
	ResultsEncodingType       GeometryEncodingType  `protobuf:"varint,8,opt,name=results_encoding_type,json=resultsEncodingType,proto3,enum=epl.geometry.GeometryEncodingType" json:"results_encoding_type,omitempty"`
	OperationSpatialReference *SpatialReferenceData `protobuf:"bytes,9,opt,name=operation_spatial_reference,json=operationSpatialReference,proto3" json:"operation_spatial_reference,omitempty"`
	ResultSpatialReference    *SpatialReferenceData `protobuf:"bytes,10,opt,name=result_spatial_reference,json=resultSpatialReference,proto3" json:"result_spatial_reference,omitempty"`
	//    oneof params {
	BufferParams           *BufferParams           `protobuf:"bytes,11,opt,name=buffer_params,json=bufferParams,proto3" json:"buffer_params,omitempty"`
	ConvexParams           *ConvexParams           `protobuf:"bytes,12,opt,name=convex_params,json=convexParams,proto3" json:"convex_params,omitempty"`
	RelateParams           *RelateParams           `protobuf:"bytes,13,opt,name=relate_params,json=relateParams,proto3" json:"relate_params,omitempty"`
	RandomPointsParams     *RandomPointsParams     `protobuf:"bytes,14,opt,name=random_points_params,json=randomPointsParams,proto3" json:"random_points_params,omitempty"`
	GeneralizeParams       *GeneralizeParams       `protobuf:"bytes,15,opt,name=generalize_params,json=generalizeParams,proto3" json:"generalize_params,omitempty"`
	IntersectionParams     *IntersectionParams     `protobuf:"bytes,16,opt,name=intersection_params,json=intersectionParams,proto3" json:"intersection_params,omitempty"`
	OffsetParams           *OffsetParams           `protobuf:"bytes,17,opt,name=offset_params,json=offsetParams,proto3" json:"offset_params,omitempty"`
	CutParams              *CutParams              `protobuf:"bytes,18,opt,name=cut_params,json=cutParams,proto3" json:"cut_params,omitempty"`
	ClipParams             *ClipParams             `protobuf:"bytes,19,opt,name=clip_params,json=clipParams,proto3" json:"clip_params,omitempty"`
	DensifyParams          *DensifyParams          `protobuf:"bytes,20,opt,name=densify_params,json=densifyParams,proto3" json:"densify_params,omitempty"`
	SimplifyParams         *SimplifyParams         `protobuf:"bytes,21,opt,name=simplify_params,json=simplifyParams,proto3" json:"simplify_params,omitempty"`
	GeneralizeByAreaParams *GeneralizeByAreaParams `protobuf:"bytes,22,opt,name=generalize_by_area_params,json=generalizeByAreaParams,proto3" json:"generalize_by_area_params,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *OperatorRequest) Reset()         { *m = OperatorRequest{} }
func (m *OperatorRequest) String() string { return proto.CompactTextString(m) }
func (*OperatorRequest) ProtoMessage()    {}
func (*OperatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{17}
}

func (m *OperatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorRequest.Unmarshal(m, b)
}
func (m *OperatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorRequest.Marshal(b, m, deterministic)
}
func (m *OperatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorRequest.Merge(m, src)
}
func (m *OperatorRequest) XXX_Size() int {
	return xxx_messageInfo_OperatorRequest.Size(m)
}
func (m *OperatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorRequest proto.InternalMessageInfo

func (m *OperatorRequest) GetGeometryBag() *GeometryBagData {
	if m != nil {
		return m.GeometryBag
	}
	return nil
}

func (m *OperatorRequest) GetGeometryRequest() *OperatorRequest {
	if m != nil {
		return m.GeometryRequest
	}
	return nil
}

func (m *OperatorRequest) GetLeftGeometryBag() *GeometryBagData {
	if m != nil {
		return m.LeftGeometryBag
	}
	return nil
}

func (m *OperatorRequest) GetLeftGeometryRequest() *OperatorRequest {
	if m != nil {
		return m.LeftGeometryRequest
	}
	return nil
}

func (m *OperatorRequest) GetRightGeometryBag() *GeometryBagData {
	if m != nil {
		return m.RightGeometryBag
	}
	return nil
}

func (m *OperatorRequest) GetRightGeometryRequest() *OperatorRequest {
	if m != nil {
		return m.RightGeometryRequest
	}
	return nil
}

func (m *OperatorRequest) GetOperatorType() ServiceOperatorType {
	if m != nil {
		return m.OperatorType
	}
	return ServiceOperatorType_Project
}

func (m *OperatorRequest) GetResultsEncodingType() GeometryEncodingType {
	if m != nil {
		return m.ResultsEncodingType
	}
	return GeometryEncodingType_unknown
}

func (m *OperatorRequest) GetOperationSpatialReference() *SpatialReferenceData {
	if m != nil {
		return m.OperationSpatialReference
	}
	return nil
}

func (m *OperatorRequest) GetResultSpatialReference() *SpatialReferenceData {
	if m != nil {
		return m.ResultSpatialReference
	}
	return nil
}

func (m *OperatorRequest) GetBufferParams() *BufferParams {
	if m != nil {
		return m.BufferParams
	}
	return nil
}

func (m *OperatorRequest) GetConvexParams() *ConvexParams {
	if m != nil {
		return m.ConvexParams
	}
	return nil
}

func (m *OperatorRequest) GetRelateParams() *RelateParams {
	if m != nil {
		return m.RelateParams
	}
	return nil
}

func (m *OperatorRequest) GetRandomPointsParams() *RandomPointsParams {
	if m != nil {
		return m.RandomPointsParams
	}
	return nil
}

func (m *OperatorRequest) GetGeneralizeParams() *GeneralizeParams {
	if m != nil {
		return m.GeneralizeParams
	}
	return nil
}

func (m *OperatorRequest) GetIntersectionParams() *IntersectionParams {
	if m != nil {
		return m.IntersectionParams
	}
	return nil
}

func (m *OperatorRequest) GetOffsetParams() *OffsetParams {
	if m != nil {
		return m.OffsetParams
	}
	return nil
}

func (m *OperatorRequest) GetCutParams() *CutParams {
	if m != nil {
		return m.CutParams
	}
	return nil
}

func (m *OperatorRequest) GetClipParams() *ClipParams {
	if m != nil {
		return m.ClipParams
	}
	return nil
}

func (m *OperatorRequest) GetDensifyParams() *DensifyParams {
	if m != nil {
		return m.DensifyParams
	}
	return nil
}

func (m *OperatorRequest) GetSimplifyParams() *SimplifyParams {
	if m != nil {
		return m.SimplifyParams
	}
	return nil
}

func (m *OperatorRequest) GetGeneralizeByAreaParams() *GeneralizeByAreaParams {
	if m != nil {
		return m.GeneralizeByAreaParams
	}
	return nil
}

type EnvelopeData struct {
	Xmin                 float64               `protobuf:"fixed64,1,opt,name=xmin,proto3" json:"xmin,omitempty"`
	Ymin                 float64               `protobuf:"fixed64,2,opt,name=ymin,proto3" json:"ymin,omitempty"`
	Xmax                 float64               `protobuf:"fixed64,3,opt,name=xmax,proto3" json:"xmax,omitempty"`
	Ymax                 float64               `protobuf:"fixed64,4,opt,name=ymax,proto3" json:"ymax,omitempty"`
	SpatialReference     *SpatialReferenceData `protobuf:"bytes,5,opt,name=spatial_reference,json=spatialReference,proto3" json:"spatial_reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EnvelopeData) Reset()         { *m = EnvelopeData{} }
func (m *EnvelopeData) String() string { return proto.CompactTextString(m) }
func (*EnvelopeData) ProtoMessage()    {}
func (*EnvelopeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9483bbde7a37438, []int{18}
}

func (m *EnvelopeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvelopeData.Unmarshal(m, b)
}
func (m *EnvelopeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvelopeData.Marshal(b, m, deterministic)
}
func (m *EnvelopeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvelopeData.Merge(m, src)
}
func (m *EnvelopeData) XXX_Size() int {
	return xxx_messageInfo_EnvelopeData.Size(m)
}
func (m *EnvelopeData) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvelopeData.DiscardUnknown(m)
}

var xxx_messageInfo_EnvelopeData proto.InternalMessageInfo

func (m *EnvelopeData) GetXmin() float64 {
	if m != nil {
		return m.Xmin
	}
	return 0
}

func (m *EnvelopeData) GetYmin() float64 {
	if m != nil {
		return m.Ymin
	}
	return 0
}

func (m *EnvelopeData) GetXmax() float64 {
	if m != nil {
		return m.Xmax
	}
	return 0
}

func (m *EnvelopeData) GetYmax() float64 {
	if m != nil {
		return m.Ymax
	}
	return 0
}

func (m *EnvelopeData) GetSpatialReference() *SpatialReferenceData {
	if m != nil {
		return m.SpatialReference
	}
	return nil
}

func init() {
	proto.RegisterEnum("epl.geometry.GeometryEncodingType", GeometryEncodingType_name, GeometryEncodingType_value)
	proto.RegisterEnum("epl.geometry.ServiceOperatorType", ServiceOperatorType_name, ServiceOperatorType_value)
	proto.RegisterEnum("epl.geometry.OffsetJoinType", OffsetJoinType_name, OffsetJoinType_value)
	proto.RegisterEnum("epl.geometry.FileType", FileType_name, FileType_value)
	proto.RegisterType((*GeometryBagData)(nil), "epl.geometry.GeometryBagData")
	proto.RegisterType((*SpatialReferenceData)(nil), "epl.geometry.SpatialReferenceData")
	proto.RegisterType((*OperatorResult)(nil), "epl.geometry.OperatorResult")
	proto.RegisterMapType((map[int64]bool)(nil), "epl.geometry.OperatorResult.RelateMapEntry")
	proto.RegisterType((*FileChunk)(nil), "epl.geometry.FileChunk")
	proto.RegisterType((*BufferParams)(nil), "epl.geometry.BufferParams")
	proto.RegisterType((*GeodeticBufferParams)(nil), "epl.geometry.GeodeticBufferParams")
	proto.RegisterType((*ConvexParams)(nil), "epl.geometry.ConvexParams")
	proto.RegisterType((*RelateParams)(nil), "epl.geometry.RelateParams")
	proto.RegisterType((*RandomPointsParams)(nil), "epl.geometry.RandomPointsParams")
	proto.RegisterType((*GeneralizeParams)(nil), "epl.geometry.GeneralizeParams")
	proto.RegisterType((*GeneralizeByAreaParams)(nil), "epl.geometry.GeneralizeByAreaParams")
	proto.RegisterType((*IntersectionParams)(nil), "epl.geometry.IntersectionParams")
	proto.RegisterType((*OffsetParams)(nil), "epl.geometry.OffsetParams")
	proto.RegisterType((*CutParams)(nil), "epl.geometry.CutParams")
	proto.RegisterType((*ClipParams)(nil), "epl.geometry.ClipParams")
	proto.RegisterType((*DensifyParams)(nil), "epl.geometry.DensifyParams")
	proto.RegisterType((*SimplifyParams)(nil), "epl.geometry.SimplifyParams")
	proto.RegisterType((*OperatorRequest)(nil), "epl.geometry.OperatorRequest")
	proto.RegisterType((*EnvelopeData)(nil), "epl.geometry.EnvelopeData")
}

func init() { proto.RegisterFile("geometry_operators.proto", fileDescriptor_d9483bbde7a37438) }

var fileDescriptor_d9483bbde7a37438 = []byte{
	// 2161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x4b, 0x73, 0x1b, 0xc7,
	0xf1, 0xd7, 0x02, 0x04, 0x09, 0x34, 0x1e, 0x1c, 0x0c, 0x41, 0x12, 0x12, 0xa5, 0xbf, 0xa9, 0xb5,
	0xa4, 0x3f, 0x23, 0xc5, 0x4c, 0xc2, 0xa4, 0x5c, 0x51, 0xe2, 0x94, 0x12, 0x3e, 0x44, 0x53, 0xb2,
	0x22, 0x6a, 0x29, 0x5b, 0x79, 0x55, 0x6d, 0x0d, 0x17, 0x0d, 0x70, 0xc8, 0x7d, 0x69, 0x66, 0x96,
	0x02, 0xfc, 0x41, 0x72, 0xca, 0x29, 0x57, 0x1f, 0x72, 0xc9, 0x31, 0x1f, 0x27, 0xb7, 0x7c, 0x80,
	0x54, 0xe5, 0x94, 0x9a, 0xd9, 0x5d, 0x60, 0x01, 0xc2, 0x2e, 0xda, 0xf2, 0x25, 0xb7, 0x99, 0x9e,
	0xee, 0xdf, 0xf6, 0x74, 0x4f, 0xcf, 0xaf, 0x67, 0xa1, 0x3b, 0xc0, 0x28, 0x40, 0x25, 0x46, 0x6e,
	0x14, 0xa3, 0x60, 0x2a, 0x12, 0x72, 0x3b, 0x16, 0x91, 0x8a, 0x68, 0x03, 0x63, 0x7f, 0x3b, 0x5f,
	0xb5, 0xff, 0x53, 0x82, 0xe5, 0xc3, 0x6c, 0xb2, 0xcb, 0x06, 0xfb, 0x4c, 0x31, 0x7a, 0x17, 0x1a,
	0x63, 0x6b, 0xde, 0x93, 0x5d, 0x6b, 0xb3, 0xbc, 0x55, 0x76, 0xea, 0xb9, 0xec, 0xa8, 0x27, 0xe9,
	0x07, 0x50, 0xef, 0x23, 0x53, 0x89, 0x40, 0xa3, 0x51, 0xdb, 0x2c, 0x6f, 0xd5, 0x1c, 0xc8, 0x44,
	0x5a, 0xe1, 0x77, 0xb0, 0x36, 0xc6, 0xc0, 0xd0, 0x8b, 0x7a, 0x3c, 0x1c, 0xb8, 0x6a, 0x14, 0x63,
	0xb7, 0xb4, 0x69, 0x6d, 0xb5, 0x76, 0xec, 0xed, 0xa2, 0x1b, 0xdb, 0xb9, 0x0b, 0x07, 0x99, 0xea,
	0xeb, 0x51, 0x8c, 0x4e, 0x67, 0x30, 0x47, 0x4a, 0x09, 0x94, 0xdf, 0x5d, 0xa8, 0x6e, 0xd9, 0x7c,
	0x52, 0x0f, 0x69, 0x17, 0x96, 0x06, 0x18, 0x9d, 0xcb, 0x28, 0xec, 0x2e, 0x18, 0x69, 0x3e, 0x4d,
	0x75, 0x4f, 0xbb, 0x95, 0xcd, 0xf2, 0x56, 0x43, 0xeb, 0x9e, 0xd2, 0x3b, 0x00, 0x28, 0x05, 0x77,
	0xe5, 0x19, 0x8b, 0xb1, 0xbb, 0x68, 0x16, 0x6a, 0x5a, 0x72, 0xa2, 0x05, 0xf4, 0x25, 0xb4, 0x65,
	0xcc, 0x14, 0x67, 0xbe, 0x2b, 0xb0, 0x8f, 0x02, 0x43, 0x0f, 0xbb, 0x4b, 0x9b, 0xd6, 0x56, 0x7d,
	0xd6, 0xe3, 0x93, 0x54, 0xcd, 0xc9, 0xb5, 0x74, 0xe4, 0x1c, 0x22, 0x67, 0xa4, 0x74, 0x03, 0x0c,
	0xba, 0x6b, 0xbc, 0xab, 0x1a, 0xef, 0xaa, 0x5a, 0xf0, 0x4c, 0x46, 0xa1, 0xfd, 0x47, 0xe8, 0xcc,
	0x83, 0xa1, 0x1d, 0xa8, 0xc4, 0x22, 0x3a, 0xff, 0x59, 0x77, 0x61, 0xd3, 0xda, 0xaa, 0x39, 0xe9,
	0x84, 0xde, 0x04, 0x63, 0xe9, 0xea, 0xdd, 0x57, 0xcc, 0xc2, 0x92, 0x9e, 0xbf, 0xb9, 0x50, 0x94,
	0xc2, 0xc2, 0xbb, 0x0b, 0xde, 0xeb, 0x2e, 0x6e, 0x5a, 0x5b, 0x15, 0xc7, 0x8c, 0xed, 0xaf, 0x4a,
	0xd0, 0x7a, 0x99, 0xe5, 0xde, 0x41, 0x99, 0xf8, 0x8a, 0xfe, 0xba, 0x90, 0xd8, 0x53, 0x36, 0xe8,
	0x5a, 0x66, 0x63, 0x77, 0xe6, 0xa7, 0x22, 0x3b, 0x0d, 0x93, 0xbc, 0xef, 0xb2, 0x01, 0xfd, 0x09,
	0x74, 0x26, 0xf1, 0xf1, 0x99, 0xe2, 0x51, 0x28, 0xcf, 0x78, 0x6c, 0x92, 0x5a, 0x75, 0x56, 0xc6,
	0xdb, 0x9f, 0x2c, 0xd1, 0x5b, 0x50, 0xed, 0x71, 0xa9, 0x98, 0x8e, 0x64, 0x79, 0xd3, 0xda, 0xb2,
	0x9c, 0xf1, 0x9c, 0x3e, 0x03, 0x30, 0x30, 0xe8, 0x06, 0x2c, 0x36, 0xc9, 0xab, 0xef, 0x3c, 0x9a,
	0x76, 0x67, 0x7a, 0x0b, 0xdb, 0x06, 0x1a, 0x5f, 0xb0, 0xf8, 0x20, 0x54, 0x62, 0xe4, 0xd4, 0x44,
	0x3e, 0xbf, 0xf5, 0x09, 0xb4, 0xa6, 0x17, 0x75, 0xf6, 0x2f, 0x70, 0x64, 0x76, 0x59, 0x76, 0xf4,
	0x50, 0x07, 0xf6, 0x92, 0xf9, 0x09, 0x66, 0xfe, 0xa6, 0x93, 0x5f, 0x94, 0x7e, 0x6e, 0xd9, 0xff,
	0x2c, 0x43, 0xed, 0x29, 0xf7, 0x71, 0xef, 0x2c, 0x09, 0x2f, 0xe8, 0x3e, 0xb4, 0x42, 0x94, 0x0a,
	0x7b, 0xae, 0xc0, 0xb7, 0x09, 0x4a, 0x35, 0x3f, 0x54, 0x13, 0xdf, 0x8c, 0x92, 0xd3, 0x4c, 0x8d,
	0xb2, 0x29, 0xfd, 0x02, 0x56, 0x85, 0xf1, 0x5a, 0x7e, 0xe7, 0x12, 0x58, 0xc9, 0x00, 0xa6, 0x2a,
	0xe0, 0x0f, 0xb0, 0xce, 0xc3, 0x38, 0x51, 0xee, 0xd5, 0xa3, 0x5a, 0xbe, 0xf6, 0x51, 0x5d, 0x35,
	0x10, 0xb3, 0x4b, 0xf4, 0x4f, 0xd0, 0x4d, 0x3f, 0x39, 0x07, 0xbc, 0x72, 0x6d, 0xf0, 0xb5, 0x14,
	0xe3, 0x0a, 0x3a, 0x85, 0x85, 0x1e, 0x53, 0xcc, 0x9c, 0xd3, 0x86, 0x63, 0xc6, 0x5a, 0x26, 0xf9,
	0x97, 0x69, 0x95, 0x95, 0x1d, 0x33, 0xa6, 0x6b, 0xb0, 0x18, 0xf5, 0xfb, 0x12, 0x55, 0xb7, 0x6a,
	0xa4, 0xd9, 0x4c, 0x57, 0x53, 0x9f, 0xfb, 0xe8, 0x86, 0x2c, 0xc0, 0x6e, 0xcd, 0xd4, 0x40, 0x55,
	0x0b, 0x7e, 0xcb, 0x02, 0xa4, 0x36, 0x34, 0xb9, 0x74, 0x7d, 0x26, 0x95, 0xeb, 0xe9, 0x2c, 0x76,
	0xc1, 0x24, 0xb9, 0xce, 0xe5, 0x67, 0x4c, 0x2a, 0x93, 0x58, 0xfb, 0xef, 0x16, 0x34, 0x76, 0x93,
	0x7e, 0x1f, 0xc5, 0x31, 0x13, 0x2c, 0x90, 0xf4, 0x36, 0xd4, 0xf2, 0xd3, 0x98, 0x5e, 0x74, 0x96,
	0x33, 0x11, 0xd0, 0xfb, 0xd0, 0x0a, 0xd8, 0xd0, 0xed, 0xe1, 0x25, 0x4f, 0x0f, 0x74, 0xb7, 0x64,
	0x54, 0x9a, 0x01, 0x1b, 0xee, 0x8f, 0x85, 0xfa, 0xc2, 0x4c, 0x42, 0x1e, 0x85, 0x6e, 0xba, 0x6d,
	0x93, 0x85, 0xaa, 0x53, 0x37, 0xb2, 0xac, 0xf4, 0x3e, 0x81, 0x0d, 0x8d, 0x74, 0x89, 0x42, 0x71,
	0x0f, 0xa5, 0xcb, 0x43, 0xb7, 0x9f, 0xf8, 0xbe, 0xeb, 0x71, 0xe1, 0xf9, 0x68, 0x0a, 0xbd, 0xe2,
	0xac, 0x07, 0x6c, 0xf8, 0x45, 0xa6, 0x71, 0x14, 0x3e, 0x4d, 0x7c, 0x7f, 0xcf, 0x2c, 0xdb, 0xff,
	0xb0, 0xa0, 0x73, 0x88, 0x51, 0x0f, 0x15, 0xf7, 0xfe, 0x07, 0xdd, 0xbf, 0x07, 0x8d, 0xbd, 0x28,
	0xbc, 0xc4, 0x61, 0xe6, 0x75, 0x07, 0x2a, 0x01, 0x8a, 0x01, 0x9a, 0xaa, 0xaa, 0x3a, 0xe9, 0xc4,
	0xbe, 0x0f, 0x8d, 0xb4, 0x80, 0x33, 0xad, 0x55, 0x58, 0xec, 0xa1, 0xfb, 0x98, 0x07, 0x46, 0xad,
	0xe6, 0x54, 0x7a, 0xf8, 0x98, 0x07, 0xf6, 0xef, 0x81, 0x3a, 0x2c, 0xec, 0x45, 0xc1, 0x71, 0xc4,
	0x43, 0x25, 0x33, 0xe5, 0x1f, 0x41, 0x27, 0x36, 0x73, 0x37, 0x46, 0xe1, 0xca, 0xb7, 0x09, 0x13,
	0xe8, 0x5e, 0x04, 0x59, 0x4c, 0xda, 0xe9, 0xda, 0x31, 0x8a, 0x13, 0xb3, 0xf2, 0x3c, 0x30, 0xc7,
	0x0e, 0xb1, 0x67, 0x6a, 0x51, 0x1f, 0x3b, 0xc4, 0x9e, 0xdd, 0x07, 0x72, 0x88, 0x21, 0x0a, 0xe6,
	0xf3, 0x2f, 0x73, 0x2f, 0x3e, 0x84, 0xe6, 0x54, 0x0c, 0x8d, 0x33, 0x96, 0xd3, 0x28, 0x86, 0x90,
	0x7e, 0x04, 0x54, 0x60, 0x10, 0x5d, 0xa2, 0xdb, 0xc3, 0x81, 0x41, 0x50, 0x28, 0xb3, 0x4b, 0xa6,
	0x9d, 0xae, 0xec, 0x4f, 0x16, 0xec, 0xbf, 0x58, 0xb0, 0x36, 0xf9, 0xd0, 0xee, 0xe8, 0x37, 0x02,
	0x59, 0xf6, 0xb9, 0x47, 0xd0, 0x8e, 0x51, 0x78, 0x18, 0x2a, 0x57, 0x60, 0x2f, 0xf1, 0x0a, 0x9f,
	0x24, 0xd9, 0x82, 0x93, 0xcb, 0xbf, 0xe5, 0x67, 0xe9, 0x03, 0x58, 0xd6, 0x5b, 0x31, 0xb1, 0x70,
	0xbd, 0x28, 0x09, 0xd3, 0x54, 0x57, 0xcc, 0x79, 0x30, 0xd1, 0xdc, 0xd3, 0x42, 0xfb, 0x97, 0x40,
	0x8f, 0x42, 0x85, 0x42, 0xa2, 0xf9, 0x4c, 0xe6, 0xd9, 0x7d, 0x68, 0xf5, 0x78, 0x80, 0xa1, 0xd4,
	0x27, 0x25, 0x60, 0xf2, 0xc2, 0xb8, 0x55, 0x71, 0x9a, 0x63, 0xe9, 0x0b, 0x26, 0x2f, 0xec, 0xaf,
	0x2c, 0x68, 0xbc, 0x34, 0xd5, 0x9a, 0xd9, 0x15, 0xef, 0x7f, 0x6b, 0xe6, 0xfe, 0x7f, 0x0c, 0xb5,
	0xf3, 0x88, 0x87, 0xc5, 0x5b, 0xf1, 0xf6, 0xcc, 0x15, 0x6b, 0xa0, 0x9e, 0x45, 0x3c, 0x34, 0xf7,
	0x61, 0xf5, 0x3c, 0x1b, 0xe9, 0x0e, 0xe4, 0x14, 0x2f, 0xd1, 0x77, 0x85, 0x4e, 0x41, 0xc6, 0x2c,
	0x60, 0x44, 0x8e, 0x96, 0xe8, 0xc4, 0xf5, 0x7d, 0xa6, 0x14, 0x86, 0x2e, 0x0a, 0x11, 0x09, 0x73,
	0x48, 0x2d, 0xa7, 0x91, 0x09, 0x0f, 0xb4, 0xcc, 0xde, 0x81, 0xda, 0x5e, 0xa2, 0x26, 0x3b, 0xf4,
	0xa2, 0x50, 0xf2, 0x1e, 0x0a, 0x57, 0x45, 0x89, 0x77, 0x96, 0x9d, 0xcf, 0x66, 0x2e, 0x7d, 0xad,
	0x85, 0xf6, 0x3e, 0xc0, 0x9e, 0xcf, 0xe3, 0xcc, 0xe8, 0x63, 0xa8, 0x62, 0x78, 0x89, 0x7e, 0x14,
	0x63, 0x46, 0x12, 0xb7, 0xa6, 0x77, 0x70, 0x90, 0xad, 0x9a, 0x8b, 0x71, 0xac, 0x6b, 0x6f, 0x43,
	0x73, 0x5f, 0x87, 0xad, 0x3f, 0xca, 0x80, 0xee, 0x00, 0xe8, 0xec, 0xf8, 0x18, 0x0e, 0xd4, 0x59,
	0x16, 0xa9, 0x5a, 0xc0, 0x86, 0x9f, 0x19, 0x81, 0xfd, 0x00, 0x5a, 0x27, 0x3c, 0x88, 0xfd, 0x89,
	0x41, 0x07, 0x2a, 0xfd, 0x48, 0x78, 0xe3, 0x2a, 0x32, 0x13, 0xfb, 0xcf, 0x4d, 0x58, 0x9e, 0xe1,
	0xa5, 0xef, 0x81, 0xf7, 0x3f, 0x05, 0x32, 0x46, 0xc8, 0x29, 0xb1, 0x74, 0x1d, 0x4a, 0x5c, 0xce,
	0x57, 0x72, 0x5f, 0x8e, 0xa0, 0xed, 0x63, 0x5f, 0xb9, 0x53, 0x0e, 0x95, 0xaf, 0xe3, 0xd0, 0xb2,
	0xb6, 0x2b, 0x08, 0xe9, 0x2b, 0x58, 0x9d, 0x86, 0xca, 0x3d, 0x5b, 0xb8, 0x8e, 0x67, 0x2b, 0x45,
	0xb8, 0xdc, 0xbb, 0xe7, 0x40, 0x05, 0x1f, 0x9c, 0xcd, 0xb8, 0x57, 0xb9, 0x8e, 0x7b, 0xc4, 0x18,
	0x16, 0xfd, 0x3b, 0x81, 0xb5, 0x19, 0xb0, 0xdc, 0xc1, 0xc5, 0xeb, 0x38, 0xd8, 0x99, 0x02, 0xcc,
	0x3d, 0x7c, 0x0a, 0xcd, 0xbc, 0xa3, 0x4f, 0xcb, 0x66, 0xc9, 0x94, 0xcd, 0xdd, 0x19, 0x56, 0x46,
	0x71, 0xc9, 0x3d, 0xcc, 0x21, 0x4d, 0xed, 0x34, 0xa2, 0xc2, 0xec, 0xeb, 0x9b, 0x93, 0xea, 0xfb,
	0x35, 0x27, 0xa7, 0xb0, 0x91, 0x7e, 0x47, 0x5f, 0x13, 0x57, 0x7b, 0x88, 0xda, 0xb5, 0x7b, 0x88,
	0x9b, 0x63, 0x98, 0x6f, 0xd5, 0xa4, 0xc0, 0x7b, 0x37, 0x29, 0x4f, 0xa0, 0x79, 0x6a, 0x38, 0xd6,
	0x8d, 0x4d, 0xa1, 0x75, 0xeb, 0xf3, 0xca, 0xba, 0x48, 0xc3, 0x4e, 0xe3, 0xb4, 0x48, 0xca, 0x4f,
	0x40, 0xdf, 0x18, 0x97, 0x38, 0xcc, 0x01, 0x1a, 0xf3, 0x00, 0x8a, 0x8c, 0xe8, 0x34, 0xbc, 0x22,
	0x3f, 0x3e, 0x81, 0x66, 0xd6, 0x16, 0x67, 0x00, 0xcd, 0x79, 0x00, 0x45, 0xb2, 0x74, 0x1a, 0xa2,
	0x48, 0x9d, 0x0e, 0x74, 0x84, 0xe1, 0x48, 0x37, 0x27, 0xc5, 0x14, 0xa7, 0x65, 0x70, 0x36, 0x67,
	0x70, 0xae, 0xb0, 0xa9, 0x43, 0xc5, 0x55, 0x86, 0x7d, 0x0e, 0xed, 0xc1, 0x98, 0xb3, 0x72, 0xc0,
	0x65, 0x03, 0xf8, 0x7f, 0xb3, 0x87, 0x65, 0x9a, 0x43, 0x1d, 0x32, 0x98, 0x65, 0xd5, 0x57, 0xb0,
	0xc2, 0x0b, 0x14, 0x93, 0xc3, 0x91, 0x79, 0xfe, 0x5d, 0xe5, 0x22, 0x87, 0xf2, 0xab, 0xfc, 0xf4,
	0x04, 0x9a, 0x69, 0x97, 0x98, 0x83, 0xb5, 0xe7, 0x05, 0xad, 0x48, 0x4d, 0x4e, 0x23, 0x2a, 0x12,
	0xd5, 0xc7, 0x00, 0x5e, 0x32, 0xb6, 0xa6, 0xc6, 0x7a, 0x7d, 0x26, 0x67, 0x39, 0x57, 0x38, 0x35,
	0x6f, 0x4c, 0x1b, 0x8f, 0xa1, 0xee, 0xf9, 0x3c, 0xce, 0x0d, 0x57, 0x8c, 0x61, 0x77, 0xc6, 0x70,
	0x4c, 0x18, 0x0e, 0x78, 0x13, 0xf2, 0xd8, 0x85, 0x56, 0x2f, 0x25, 0x81, 0xdc, 0xba, 0x63, 0xac,
	0x37, 0xa6, 0xad, 0xa7, 0x88, 0xc2, 0x69, 0xf6, 0xa6, 0x78, 0xe3, 0x00, 0x96, 0x65, 0x46, 0x0c,
	0x39, 0xc8, 0xaa, 0x01, 0x99, 0x61, 0xd2, 0x69, 0xf6, 0x70, 0x5a, 0x72, 0x9a, 0x4d, 0x5c, 0xb8,
	0x59, 0x48, 0xef, 0xe9, 0xc8, 0x65, 0x02, 0x59, 0x0e, 0xb8, 0x66, 0x00, 0xef, 0x7d, 0x5d, 0x9a,
	0x8b, 0x1d, 0x8c, 0xb3, 0x36, 0x98, 0x2b, 0xb7, 0xff, 0x66, 0x41, 0xa3, 0xc8, 0x85, 0xba, 0x03,
	0x1b, 0x06, 0x3c, 0xef, 0x6e, 0xcc, 0x58, 0xcb, 0x46, 0x5a, 0x56, 0x4a, 0x65, 0xa3, 0x4c, 0x36,
	0x0c, 0xd8, 0x30, 0xa3, 0x78, 0x33, 0x4e, 0xf5, 0xd8, 0x30, 0xe3, 0x74, 0x33, 0x9e, 0xff, 0x76,
	0xaf, 0x7c, 0xf7, 0xb7, 0xfb, 0xc3, 0x57, 0xa6, 0xe9, 0xbe, 0xfa, 0x07, 0xa2, 0x0e, 0x4b, 0x49,
	0x78, 0x11, 0x46, 0xef, 0x42, 0x72, 0x83, 0x2e, 0x99, 0x5f, 0x0c, 0xc4, 0x4a, 0x07, 0x8a, 0x94,
	0xf4, 0x72, 0xf6, 0xff, 0x81, 0x94, 0x69, 0x33, 0x7d, 0xff, 0x9b, 0xdf, 0x0d, 0x64, 0xe1, 0xe1,
	0xbf, 0x2b, 0xb0, 0x32, 0xe7, 0x6e, 0xd6, 0x36, 0xc7, 0x22, 0x3a, 0x47, 0x4f, 0x91, 0x1b, 0x94,
	0x40, 0xe3, 0x60, 0x18, 0x47, 0x42, 0xbd, 0x8e, 0x9e, 0x69, 0x14, 0x8b, 0x52, 0x68, 0x1d, 0x05,
	0x5a, 0xf2, 0x54, 0x44, 0x81, 0x91, 0x95, 0xe8, 0x1d, 0xb8, 0x99, 0xca, 0x5e, 0xb0, 0x38, 0x77,
	0x73, 0xbc, 0x5c, 0xa6, 0xab, 0xd0, 0xce, 0x41, 0x0e, 0x4e, 0x9c, 0xa3, 0x93, 0xd4, 0x01, 0xba,
	0x0e, 0x2b, 0x13, 0xa4, 0xc9, 0x42, 0x85, 0xd6, 0xa0, 0xf2, 0xb9, 0x6e, 0xf8, 0xc9, 0x22, 0x6d,
	0x01, 0xec, 0xf3, 0x7e, 0x16, 0x05, 0xb2, 0x44, 0x97, 0xa1, 0x7e, 0x2c, 0xa2, 0x21, 0x0f, 0xb8,
	0x1a, 0xed, 0xec, 0x93, 0x2a, 0x05, 0x58, 0x4c, 0x2f, 0x1f, 0x52, 0xd3, 0xe3, 0x83, 0xb7, 0x09,
	0xf3, 0x25, 0x01, 0xda, 0x80, 0xea, 0x3e, 0x97, 0xba, 0x45, 0x53, 0xa4, 0xae, 0x61, 0xc6, 0xa5,
	0x2b, 0x49, 0x43, 0x6b, 0xbe, 0xe1, 0xea, 0x8c, 0x87, 0xa4, 0xa9, 0x35, 0xf7, 0xa2, 0x50, 0x31,
	0x1e, 0x4a, 0xd2, 0xd2, 0xbb, 0xdf, 0x13, 0x91, 0x94, 0x28, 0xc9, 0xb2, 0x9e, 0x98, 0x3e, 0x0b,
	0x25, 0x21, 0x5a, 0xef, 0xe5, 0x25, 0x0a, 0x9f, 0xc5, 0x92, 0xb4, 0x35, 0x42, 0x7a, 0xed, 0x12,
	0x9a, 0x7d, 0xcb, 0xb4, 0x91, 0x64, 0x45, 0x87, 0xac, 0x78, 0x4d, 0x90, 0x0e, 0xad, 0xc2, 0x82,
	0x2e, 0x3a, 0xb2, 0xaa, 0x13, 0xb3, 0x97, 0x28, 0xb2, 0x46, 0x57, 0x60, 0x39, 0xab, 0xa4, 0xdd,
	0x51, 0xda, 0x55, 0x91, 0x75, 0x1d, 0x5a, 0xf3, 0xb2, 0x92, 0xf9, 0xcb, 0x8a, 0xdc, 0xa2, 0x1b,
	0xb0, 0x9e, 0xbf, 0xb6, 0x66, 0x0d, 0x36, 0xc6, 0x06, 0x8a, 0x7b, 0x99, 0xec, 0x8e, 0x76, 0x26,
	0x2f, 0x2f, 0xf2, 0x81, 0x8e, 0x57, 0x3e, 0x7b, 0x79, 0xb8, 0x47, 0x36, 0xb5, 0xdf, 0xe9, 0xbd,
	0x43, 0xee, 0xea, 0xa8, 0x4c, 0x0a, 0x87, 0xd8, 0xb4, 0x53, 0x7c, 0x73, 0xa4, 0x05, 0x43, 0x3e,
	0xd4, 0x10, 0x79, 0xf6, 0xde, 0x5c, 0x9c, 0x92, 0x7b, 0xb4, 0x0d, 0xcd, 0x49, 0xde, 0xb4, 0xe8,
	0xfe, 0xb4, 0x8e, 0x22, 0x0f, 0x66, 0x75, 0x14, 0xf9, 0x7f, 0x7d, 0x0a, 0x26, 0xa2, 0x43, 0x4c,
	0xcf, 0xd3, 0x96, 0x8e, 0x44, 0x6e, 0x9a, 0x0b, 0x7f, 0xa0, 0x8f, 0xc6, 0xc9, 0x28, 0xd0, 0xe7,
	0x88, 0x7b, 0x85, 0xfc, 0x3f, 0xd4, 0x2e, 0xa7, 0x64, 0xf5, 0x69, 0xe2, 0xfb, 0xe4, 0x91, 0xde,
	0xed, 0x6e, 0x94, 0x84, 0x3d, 0x26, 0x46, 0xe4, 0x87, 0x3a, 0xf4, 0x45, 0x06, 0x21, 0x1f, 0x19,
	0xf4, 0xd0, 0xf3, 0x23, 0xc9, 0xc3, 0x41, 0xfa, 0x02, 0x24, 0xdb, 0x0f, 0x7f, 0x05, 0xad, 0xe9,
	0x5e, 0x5e, 0x9f, 0x38, 0x47, 0xc3, 0x90, 0x1b, 0x7a, 0xb8, 0xab, 0x3b, 0x77, 0x62, 0xe9, 0xe1,
	0x0b, 0xae, 0x50, 0x90, 0x92, 0x0e, 0x5b, 0xfa, 0x5c, 0x23, 0xe5, 0x87, 0x37, 0xa1, 0xfa, 0x94,
	0xfb, 0x68, 0x0c, 0x9b, 0x50, 0x33, 0xa7, 0x56, 0xbf, 0xfc, 0xc9, 0x8d, 0x9d, 0x7f, 0x95, 0xa0,
	0x9d, 0x17, 0x40, 0x5e, 0x54, 0x9a, 0x61, 0xc8, 0xc1, 0x10, 0xbd, 0x44, 0x65, 0x85, 0xa6, 0xdf,
	0x4b, 0xdf, 0xdc, 0x70, 0xdd, 0xba, 0xfd, 0x4d, 0x7f, 0x9e, 0xec, 0x1b, 0xf4, 0x73, 0x20, 0x27,
	0x4a, 0x20, 0x0b, 0xc6, 0x88, 0xf2, 0x3d, 0x21, 0xb7, 0xac, 0x1f, 0x5b, 0xf4, 0x0d, 0xd0, 0x59,
	0xd8, 0x83, 0xe1, 0xf7, 0x01, 0x7c, 0x02, 0x9d, 0x14, 0x58, 0x47, 0xae, 0xe0, 0xf3, 0x0c, 0xa9,
	0x8d, 0x7f, 0x7b, 0x5d, 0x07, 0x74, 0x77, 0x07, 0x88, 0x17, 0x05, 0x53, 0x8a, 0xbb, 0x6b, 0x57,
	0xc2, 0x7f, 0x2c, 0x22, 0x15, 0x1d, 0x5b, 0x7f, 0x2d, 0x95, 0x9d, 0xd7, 0x87, 0xa7, 0x8b, 0xe6,
	0xcf, 0xf3, 0x4f, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x9f, 0x41, 0x80, 0x95, 0x16, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GeometryOperatorsClient is the client API for GeometryOperators service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeometryOperatorsClient interface {
	// Execute a single geometry operation
	ExecuteOperation(ctx context.Context, in *OperatorRequest, opts ...grpc.CallOption) (*OperatorResult, error)
	// Stream in requests and return a stream of results
	StreamOperations(ctx context.Context, opts ...grpc.CallOption) (GeometryOperators_StreamOperationsClient, error)
	StreamOperationsEx(ctx context.Context, opts ...grpc.CallOption) (GeometryOperators_StreamOperationsExClient, error)
	// stream in file chunks for a geometry file type and stream back results for each geometry encountered
	StreamFileOperations(ctx context.Context, opts ...grpc.CallOption) (GeometryOperators_StreamFileOperationsClient, error)
}

type geometryOperatorsClient struct {
	cc *grpc.ClientConn
}

func NewGeometryOperatorsClient(cc *grpc.ClientConn) GeometryOperatorsClient {
	return &geometryOperatorsClient{cc}
}

func (c *geometryOperatorsClient) ExecuteOperation(ctx context.Context, in *OperatorRequest, opts ...grpc.CallOption) (*OperatorResult, error) {
	out := new(OperatorResult)
	err := c.cc.Invoke(ctx, "/epl.geometry.GeometryOperators/ExecuteOperation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geometryOperatorsClient) StreamOperations(ctx context.Context, opts ...grpc.CallOption) (GeometryOperators_StreamOperationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GeometryOperators_serviceDesc.Streams[0], "/epl.geometry.GeometryOperators/StreamOperations", opts...)
	if err != nil {
		return nil, err
	}
	x := &geometryOperatorsStreamOperationsClient{stream}
	return x, nil
}

type GeometryOperators_StreamOperationsClient interface {
	Send(*OperatorRequest) error
	Recv() (*OperatorResult, error)
	grpc.ClientStream
}

type geometryOperatorsStreamOperationsClient struct {
	grpc.ClientStream
}

func (x *geometryOperatorsStreamOperationsClient) Send(m *OperatorRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *geometryOperatorsStreamOperationsClient) Recv() (*OperatorResult, error) {
	m := new(OperatorResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *geometryOperatorsClient) StreamOperationsEx(ctx context.Context, opts ...grpc.CallOption) (GeometryOperators_StreamOperationsExClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GeometryOperators_serviceDesc.Streams[1], "/epl.geometry.GeometryOperators/StreamOperationsEx", opts...)
	if err != nil {
		return nil, err
	}
	x := &geometryOperatorsStreamOperationsExClient{stream}
	return x, nil
}

type GeometryOperators_StreamOperationsExClient interface {
	Send(*OperatorRequest) error
	Recv() (*OperatorResult, error)
	grpc.ClientStream
}

type geometryOperatorsStreamOperationsExClient struct {
	grpc.ClientStream
}

func (x *geometryOperatorsStreamOperationsExClient) Send(m *OperatorRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *geometryOperatorsStreamOperationsExClient) Recv() (*OperatorResult, error) {
	m := new(OperatorResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *geometryOperatorsClient) StreamFileOperations(ctx context.Context, opts ...grpc.CallOption) (GeometryOperators_StreamFileOperationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GeometryOperators_serviceDesc.Streams[2], "/epl.geometry.GeometryOperators/StreamFileOperations", opts...)
	if err != nil {
		return nil, err
	}
	x := &geometryOperatorsStreamFileOperationsClient{stream}
	return x, nil
}

type GeometryOperators_StreamFileOperationsClient interface {
	Send(*FileChunk) error
	Recv() (*OperatorResult, error)
	grpc.ClientStream
}

type geometryOperatorsStreamFileOperationsClient struct {
	grpc.ClientStream
}

func (x *geometryOperatorsStreamFileOperationsClient) Send(m *FileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *geometryOperatorsStreamFileOperationsClient) Recv() (*OperatorResult, error) {
	m := new(OperatorResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GeometryOperatorsServer is the server API for GeometryOperators service.
type GeometryOperatorsServer interface {
	// Execute a single geometry operation
	ExecuteOperation(context.Context, *OperatorRequest) (*OperatorResult, error)
	// Stream in requests and return a stream of results
	StreamOperations(GeometryOperators_StreamOperationsServer) error
	StreamOperationsEx(GeometryOperators_StreamOperationsExServer) error
	// stream in file chunks for a geometry file type and stream back results for each geometry encountered
	StreamFileOperations(GeometryOperators_StreamFileOperationsServer) error
}

func RegisterGeometryOperatorsServer(s *grpc.Server, srv GeometryOperatorsServer) {
	s.RegisterService(&_GeometryOperators_serviceDesc, srv)
}

func _GeometryOperators_ExecuteOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometryOperatorsServer).ExecuteOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/epl.geometry.GeometryOperators/ExecuteOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometryOperatorsServer).ExecuteOperation(ctx, req.(*OperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeometryOperators_StreamOperations_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GeometryOperatorsServer).StreamOperations(&geometryOperatorsStreamOperationsServer{stream})
}

type GeometryOperators_StreamOperationsServer interface {
	Send(*OperatorResult) error
	Recv() (*OperatorRequest, error)
	grpc.ServerStream
}

type geometryOperatorsStreamOperationsServer struct {
	grpc.ServerStream
}

func (x *geometryOperatorsStreamOperationsServer) Send(m *OperatorResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *geometryOperatorsStreamOperationsServer) Recv() (*OperatorRequest, error) {
	m := new(OperatorRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GeometryOperators_StreamOperationsEx_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GeometryOperatorsServer).StreamOperationsEx(&geometryOperatorsStreamOperationsExServer{stream})
}

type GeometryOperators_StreamOperationsExServer interface {
	Send(*OperatorResult) error
	Recv() (*OperatorRequest, error)
	grpc.ServerStream
}

type geometryOperatorsStreamOperationsExServer struct {
	grpc.ServerStream
}

func (x *geometryOperatorsStreamOperationsExServer) Send(m *OperatorResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *geometryOperatorsStreamOperationsExServer) Recv() (*OperatorRequest, error) {
	m := new(OperatorRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GeometryOperators_StreamFileOperations_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GeometryOperatorsServer).StreamFileOperations(&geometryOperatorsStreamFileOperationsServer{stream})
}

type GeometryOperators_StreamFileOperationsServer interface {
	Send(*OperatorResult) error
	Recv() (*FileChunk, error)
	grpc.ServerStream
}

type geometryOperatorsStreamFileOperationsServer struct {
	grpc.ServerStream
}

func (x *geometryOperatorsStreamFileOperationsServer) Send(m *OperatorResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *geometryOperatorsStreamFileOperationsServer) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GeometryOperators_serviceDesc = grpc.ServiceDesc{
	ServiceName: "epl.geometry.GeometryOperators",
	HandlerType: (*GeometryOperatorsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteOperation",
			Handler:    _GeometryOperators_ExecuteOperation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamOperations",
			Handler:       _GeometryOperators_StreamOperations_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamOperationsEx",
			Handler:       _GeometryOperators_StreamOperationsEx_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamFileOperations",
			Handler:       _GeometryOperators_StreamFileOperations_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "geometry_operators.proto",
}
